SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A, (
    SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY Y
) AS B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.Y -- 조건절에서는 아직 별칭을 쓸 수 없다!
ORDER BY YEAR ASC, YEAR_DEV ASC;