SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, B.MAX_SIZE-A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
LEFT OUTER JOIN (
                 SELECT DIFFERENTIATION_DATE, MAX(SIZE_OF_COLONY) AS MAX_SIZE
                 FROM ECOLI_DATA
                 GROUP BY DIFFERENTIATION_DATE
                ) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY YEAR(A.DIFFERENTIATION_DATE), YEAR_DEV;