SELECT JULY.FLAVOR
FROM JULY LEFT OUTER JOIN FIRST_HALF
ON JULY.SHIPMENT_ID = FIRST_HALF.SHIPMENT_ID
GROUP BY JULY.FLAVOR
ORDER BY SUM(IFNULL(JULY.TOTAL_ORDER, 0) + IFNULL(FIRST_HALF.TOTAL_ORDER, 0)) DESC
LIMIT 3;

-- NULLABLE이 FALSE여도 레코드 확인해보자..! 의심하는 사람이 정답을 맞춘다