SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS AS I RIGHT OUTER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.INTAKE_CONDITION IS NULL
ORDER BY O.ANIMAL_ID;

-- NULL이 포함된 레코드는 JOIN 시 레코드 전체 필드값이 NULL로 채워진다