SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO AS INFO LEFT OUTER JOIN ITEM_TREE AS TREE
ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE INFO.ITEM_ID NOT IN (
                            SELECT PARENT_ITEM_ID
                            FROM ITEM_TREE
                            WHERE PARENT_ITEM_ID IS NOT NULL
                          )
ORDER BY INFO.ITEM_ID DESC;