SELECT JULY.FLAVOR
FROM JULY LEFT OUTER JOIN FIRST_HALF -- FIRST_HALF 테이블의 SHIPMENT_ID는 (JULY 테이블의 SHIPMENT_ID의) 외래 키입니다
ON JULY.SHIPMENT_ID = FIRST_HALF.SHIPMENT_ID
GROUP BY JULY.FLAVOR
ORDER BY SUM(IFNULL(JULY.TOTAL_ORDER, 0) + IFNULL(FIRST_HALF.TOTAL_ORDER, 0)) DESC
LIMIT 3;

-- FK의 값은 반드시 PK 값 안에 존재해야 한다