SELECT JULY.FLAVOR
FROM JULY LEFT OUTER JOIN FIRST_HALF
ON JULY.SHIPMENT_ID = FIRST_HALF.SHIPMENT_ID
GROUP BY JULY.FLAVOR
ORDER BY SUM(IFNULL(JULY.TOTAL_ORDER, 0) + IFNULL(FIRST_HALF.TOTAL_ORDER, 0)) DESC
LIMIT 3;