SELECT JULY.FLAVOR
FROM JULY LEFT OUTER JOIN FIRST_HALF
ON JULY.SHIPMENT_ID = FIRST_HALF.SHIPMENT_ID
GROUP BY JULY.FLAVOR
ORDER BY SUM(JULY.TOTAL_ORDER + IFNULL(FIRST_HALF.TOTAL_ORDER, 0)) DESC
LIMIT 3;

/*
FIRST_HALF 테이블의 SHIPMENT_ID는 JULY 테이블의 SHIPMENT_ID의 외래 키(Foreign Key)입니다.

FIRST_HALF의 SHIPMENT_ID 값은 반드시 JULY에 존재하는 SHIPMENT_ID만 사용할 수 있다
JULY가 부모 테이블이고 FIRST_HALF.SHIPMENT_ID는 FK이다 -> JULY 테이블을 기준으로 조인
*/