SELECT H.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM (CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID), CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P -- Cartesian Product
WHERE C.CAR_TYPE = P.CAR_TYPE
AND H.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-11-01' < END_DATE AND START_DATE < '2022-12-01'
    )
AND P.DURATION_TYPE = '30일 이상'
GROUP BY H.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV')
AND (500000 <= FEE AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;