SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P, REST_REVIEW AS R
WHERE P.MEMBER_ID = R.MEMBER_ID
AND R.MEMBER_ID = (
                    SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    LIMIT 1
                )
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;