SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I LEFT OUTER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID NOT IN ( -- 입양 못간 동물
                            SELECT ANIMAL_ID -- 입양 간 동물
                            FROM ANIMAL_OUTS
)
ORDER BY I.DATETIME
LIMIT 3;