SELECT P.PRODUCT_CODE AS PRODUCT_CODE, SUM(P.PRICE * S.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS S LEFT OUTER JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;