SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO AS F, FISH_NAME_INFO AS N
WHERE F.FISH_TYPE = N.FISH_TYPE
AND (F.FISH_TYPE, F.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) -- 2. 집계 함수. FISH_TYPE별 가장 큰 길이 반환
    FROM FISH_INFO
    GROUP BY FISH_TYPE -- 1. GROUP BY
)
ORDER BY F.ID ASC;