SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER AS U
WHERE U.USER_ID IN (
                    SELECT WRITER_ID
                    FROM USED_GOODS_BOARD AS B
                    GROUP BY WRITER_ID
                    HAVING COUNT(*) >= 3
                   )
ORDER BY U.USER_ID DESC;