SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM (APPOINTMENT AS A LEFT OUTER JOIN PATIENT AS P
ON A.PT_NO = P.PT_NO), DOCTOR AS D
WHERE A.MDDR_ID = D.DR_ID
AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD ASC;