SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM BOOK, AUTHOR, (SELECT BOOK_ID, SUM(SALES) AS SALES
                    FROM BOOK_SALES
                    WHERE SALES_DATE LIKE '2022-01%'
                    GROUP BY BOOK_ID
) AS BOOK_SALES
WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC, BOOK.CATEGORY DESC;