SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK LEFT OUTER JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01%'
GROUP BY BOOK.CATEGORY -- 카테고리별로
ORDER BY BOOK.CATEGORY; -- 카테고리명을 오름차순으로