SELECT MCDP_CD AS 진료과코드, COUNT(*) AS 5월예약건수
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-05%'
GROUP BY 진료과코드 -- GROUP BY, ORDER BY는 alias 사용 가능
ORDER BY COUNT(*) ASC, 진료과코드 ASC; -- GROUP BY, ORDER BY는 alias 사용 가능