SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, INFO.GENDER, COUNT(DISTINCT INFO.USER_ID) AS USERS
FROM ONLINE_SALE AS SALE LEFT OUTER JOIN USER_INFO AS INFO
ON INFO.USER_ID = SALE.USER_ID
GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE), INFO.GENDER
HAVING INFO.GENDER IS NOT NULL
ORDER BY YEAR(SALE.SALES_DATE) ASC, MONTH(SALE.SALES_DATE) ASC, INFO.GENDER ASC;

/*
테이블의 컬럼이 많아 헷갈리는 경우, 동등 조인을 사용하는 것도 하나의 좋은 방법이다

SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, INFO.GENDER, COUNT(DISTINCT INFO.USER_ID) AS USERS
FROM USER_INFO AS INFO, ONLINE_SALE AS SALE
WHERE INFO.USER_ID = SALE.USER_ID
AND INFO.GENDER IS NOT NULL
GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE), INFO.GENDER
ORDER BY YEAR(SALE.SALES_DATE) ASC, MONTH(SALE.SALES_DATE) ASC, INFO.GENDER ASC;
*/