SELECT SUM(HR_GRADE.SCORE) AS SCORE, HR_GRADE.EMP_NO, HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
FROM HR_GRADE, HR_EMPLOYEES
WHERE HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
AND HR_GRADE.YEAR = '2022' -- GROUP BY로 완성된 테이블에서는 YEAR를 찾을 수 없으므로 AND로 필터링 (HAVING HR_GRADE.YEAR = '2022' : X)
GROUP BY HR_GRADE.EMP_NO, HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
ORDER BY SCORE DESC
LIMIT 1;