SELECT SUM(HR_GRADE.SCORE) AS SCORE, HR_GRADE.EMP_NO, HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
FROM HR_GRADE, HR_EMPLOYEES
WHERE HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
AND HR_GRADE.YEAR = '2022'
GROUP BY HR_GRADE.EMP_NO, HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
ORDER BY SCORE DESC
LIMIT 1;