SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM ONLINE_SALE AS S, USER_INFO AS I
WHERE S.USER_ID = I.USER_ID
AND I.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, I.GENDER
ORDER BY YEAR ASC, MONTH ASC, I.GENDER ASC;