SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
AND MONTH(H.START_DATE) = 10
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;