SELECT H.HISTORY_ID,
       FLOOR(
           (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
           * C.DAILY_FEE
           * IFNULL(100 - P.DISCOUNT_RATE, 100)
           / 100
       ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
AND P.DURATION_TYPE = CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                           WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                           WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
                           END
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;

-- 할인 정책이 테이블 P에 없는 H+C 테이블의 레코드는 NULL로 유지되어야 함. LEFT OUTER JOIN 사용
-- H+C 레코드는 LEFT OUTER JOIN과의 가독성을 위해 INNER JOIN으로 작성