SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) >= 7 -- SQL 표준 : 조건절에서는 별칭 불가능
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC; -- ORDER BY, GROUP BY에서는 별칭 가능