SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1), 2) AS 'PM10', ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR
ORDER BY YEAR ASC;

-- 일반적으로 속성 alias는 ''없이 만들지만, PM2.5처럼 .이 들어가는 이름은 반드시 ''을 사용해야 한다