SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;

-- YEAR(DATE) : DATE 타입에서 연도를 INT로 반환
-- YEAR, MONTH, DAY : DATE (2026-07-02)
-- HOUR, MINUTE, SECOND : DATETIME (2026-07-02 14:35:20)