SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;

-- MONTH(DATE)) : 월 성분 추출
-- 조건문에서.. 속성 IS NOT NULL : 속성 값이 NULL인 레코드 제외 후 결과 출력