SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS I, REST_REVIEW AS R
WHERE I.REST_ID = R.REST_ID
AND I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;

/*
일반적으로 SELECT 절은 GROUP BY에서 사용된 속성 또는 집계함수만 사용 가능하다

그러나, REST_INFO 테이블은 REST_ID에 따라 나머지 속성이 반드시 결정되므로 GROUP BY에 없는 속성도 사용 가능하다
*/