SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 -- INTEGER
AND GENDER = 'W' -- VARCHAR
AND TLNO IS NOT NULL -- Nullable : TRUE
ORDER BY MEMBER_ID;

-- DATE_FORMAT(DATE 타입의 속성, '날짜 형식')
-- MONTH(DATE 타입의 속성) : 월(month) 추출