SELECT REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO LEFT OUTER JOIN REST_REVIEW
ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE REST_INFO.ADDRESS LIKE '서울%'
AND REST_REVIEW.REVIEW_SCORE IS NOT NULL
GROUP BY REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS
ORDER BY SCORE DESC, REST_INFO.FAVORITES DESC;

-- 식당마다의 리뷰 '평균'을 구해야 하므로 GROUP BY를 사용해 묶어야 한다
-- SELECT 절에 나오는 컬럼들은 GROUP BY에서 나온 속성들 또는 집계 함수만 사용할 수 있다