SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B LEFT OUTER JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE LIKE '2022-10%' -- 2022년 10월에 작성된 '게시글 제목'이므로 REPLY가 아닌 BOARD의 CREATED_DATE
AND R.CONTENTS IS NOT NULL -- 테이블을 보고 Nullable 데이터 체크하기
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;