SELECT A.ID, IFNULL(B.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS A LEFT OUTER JOIN ( -- 자식이 없다면 자식의 수는 0으로 출력해주세요
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA AS B
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
) AS B
ON A.ID = B.PARENT_ID;

-- 조건에 맞는 행이 없어도 전부 출력한다면 외부 조인을 선택해야 한다