WITH RECURSIVE PARENT AS (
    -- 기본 레코드 생성
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION -- 레코드 분기
    
    -- 재귀적으로 레코드 생성
    SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS CHILD, PARENT
    WHERE PARENT.ID = CHILD.PARENT_ID
) -- PARENT 테이블 생성

SELECT COUNT(*) AS COUNT, GENERATION
FROM PARENT
WHERE ID NOT IN ( -- 1, 3, 5, 7, 8
    SELECT IFNULL(PARENT_ID, 0) AS PARENT_ID -- 0, 2, 4, 6
    FROM ECOLI_DATA
)
GROUP BY GENERATION
ORDER BY GENERATION;