WITH RECURSIVE PARENT AS ( -- 테이블 추가
    -- 기본 레코드 생성
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION -- 중복 없는 합집합
    
    -- 기본 레코드를 기반으로 재귀적인 레코드 생성
    SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS CHILD, PARENT
    WHERE PARENT.ID = CHILD.PARENT_ID -- 조건을 만족할 때까지 생성
) -- PARENT 테이블 생성 완료

SELECT COUNT(*) AS COUNT, GENERATION
FROM PARENT
WHERE ID NOT IN ( -- 1, 3, 5, 7, 8
    SELECT IFNULL(PARENT_ID, 0) AS PARENT_ID -- 0, 2, 4, 6
    FROM ECOLI_DATA
)
GROUP BY GENERATION
ORDER BY GENERATION;